### ISSUE TITLE
3.3 - Services - needs update login.html

### ISSUE THREAD

**Issue by leocaseiro** [NativeScript/nativescript-angular-guide#10]
After follow the instructors of the Service methods: `signUp` and `login`. Just before **Exercise: Use an Angular 2 service** we need to update the login.html:

``` html
<Button text="Sign in" id="submit-button" (tap)="login()"></Button>
<Button text="Sign up for Groceries" (tap)="signUp()"></Button>
```

**Comment by tjvantoll** [comment]
Hey @leocaseiro,

At that point though I believe those buttons should point out the `submit()` and `toggleDisplay()` functions.

``` XML
<Button [text]="isLoggingIn ? 'Sign in' : 'Sign up'" id="submit-button" (tap)="submit()"></Button>
<Button [text]="isLoggingIn ? 'Sign up' : 'Back to login'" (tap)="toggleDisplay()"></Button>
```

Am I missing something?

**Comment by leocaseiro** [comment]
Hey @tjvantoll, I believe the signUp calls the toggleDisplay():

![screen shot 2016-04-15 at 8 48 40 am](https://cloud.githubusercontent.com/assets/940070/14546172/f3ea08d4-02e6-11e6-9ee7-51c92ce1d4f8.png)

**Comment by leocaseiro** [comment]
Please, ignore this issue.
I'm sorry, but I didn't see that:

``` javascript
submit() {
  if (this.isLoggingIn) {
    this.login();
  } else {
    this.signUp();
  }
}
```
