### ISSUE TITLE
Having trouble with using [(ngModel)] for email textfield as suggested in chapter 3.1

### ISSUE THREAD

**Issue by lakhanpalv** [NativeScript/nativescript-angular-guide#15]
I am trying to get sample-grocery app working by reading this guide but as suggested at step 3.1 when i am trying to bind ngModel with email textfield like [(ngModel)]="email". It's not working I am getting following error as soon as the app is launched in android emulator:

---

JS: Error: Uncaught (in promise): EXCEPTION: Error in ./AppComponent class AppComponent - inline template:2:63
JS: ORIGINAL EXCEPTION: No value accessor for ''
JS: ORIGINAL STACKTRACE:
JS: Error: No value accessor for ''
JS:     at new BaseException (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/facade/exceptions.js:17:                                                   23)
JS:     at _throwError (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/common/forms/directives/shared                                                   .js:47:11)
JS:     at Object.setUpControl (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/common/forms/directive                                                   s/shared.js:22:9)
JS:     at NgModel.ngOnChanges (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/common/forms/directive                                                   s/ng_model.js:64:22)
JS:     at AppView._View_AppComponent0.detectChangesInternal (AppComponent.template.js:140:47)
JS:     at AppView.detectChanges (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/core/linker/view.js:                                                   267:22)
JS:     at AppView.detectViewChildrenChanges (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/core/lin                                                   ker/view.js:296:34)
JS:     at AppView.detectChangesInternal (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/core/linker/                                                   view.js:287:14)
JS:     at AppView.detectChanges (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/core/linker/view.js:                                                   267:22)
JS:     at ViewRef_.detectChanges (/data/data/org.nativescript.groceries/files/app/tns_modules/angular2/src/core/linker/view_re                                                   f.js:131:65)
JS: ERROR CONTEXT:
JS: [object Object]

---

Can anyone suggest anything wrong, i might be doing, by looking at debug trace above?

Thanks,
Vivek

**Comment by lakhanpalv** [comment]
[errorlog.txt](https://github.com/NativeScript/nativescript-angular-guide/files/243798/errorlog.txt)
this is the complete error log, which i am seeing when trying to launch app after making ngModel change.

**Comment by lakhanpalv** [comment]
I figured the issue myself. I was using <TextField> as <textfield> even <Textfield> is giving similar to listed above. So it seems <TextField> is case sensitive if i am using ngModel. not exactly sure why. But at least it's working for me now, would love to know why not using Pascal Casing is making it work not otherwise.

**Comment by mdskinner** [comment]
how did you fix it?

**Comment by lakhanpalv** [comment]
https://viveklakhanpal.wordpress.com/2016/05/30/nativescript-app-with-angular2-listing-phone-contacts/ 

"**Naming convention is important**: When you are creating your templates in xml/html (you can name the template file as html as most of the editors will give you better help) make sure you either use CamleCase or kebab-case styling to name the tags for e.g. either <StackLayout> or <stack-layout> not like <stacklayout> or <textfield>" ... "one of the tutorial its updated now that says, you should be using either of the 2 naming conventions to name your tags in xml/html template markup nothing else"
