### ISSUE TITLE
Why do you have to import HTTP_PROVIDERS in `app.component.ts`

### ISSUE THREAD

**Issue by burkeholland** [NativeScript/nativescript-angular-guide#6]
I'm still unclear after the description in section **3.3**. The explanation says that it's because the `UserService` makes use of it, but it's unclear as to why this would be injected as opposed to just importing it. Did I miss a paragraph?

**Comment by dreambo8563** [comment]
@burkeholland  maybe I can help to explain this.

https://angular.io/docs/ts/latest/guide/hierarchical-dependency-injection.html  here is the material for the injection. if we inject the HTTP_PROVIDERS  in the high level component A, then we can use the http service in all components under the component A without inject it in providers again.

**Comment by tjvantoll** [comment]
Hey @burkeholland. I just pushed de2498b4f4bdd6e2a022ecb1ac648187e3594820 to (hopefully) address this. If you still don’t find the explanation clear let me know.
